var iol=iol||{};iol.iolcookcs={};iol.dmp2={};iol.track={};iol.iolcookcs.ready=function(a){if("complete"==document.readyState)return a();window.addEventListener?window.addEventListener("load",a,!1):window.attachEvent?window.attachEvent("onload",a):window.onload=a};
iol.iolcookcs.ready(function(){(function(a){if(a.cookieChoices)return a.iol.cookieChoices;var b=a.document,f="textContent"in b.body,c=function(){function c(a){try{var h=b.createElement("img");h.src=("https:"==b.location.protocol?"https:":"http:")+"//adimg.virgilio.it/tracks/bi/images/bi_clk.gif?pmk="+a+"&rand="+Math.floor(1E7*Math.random()+1);h.width=1;h.height=1;var d=b.createDocumentFragment();d.appendChild(h);b.body.appendChild(d.cloneNode(!0))}catch(G){}}function l(a,b,d){f?a.textContent=b:a.innerText=
b;a.style.cssText=d}function n(a,h){var d=b.createElement("span");l(d,a,h);return d}function m(a,h,d){var c=b.createElement("a");l(c,h);c.id=a;c.href="#";c.style.cssText=d;return c}function k(a,h,d,c){var e=b.createElement("a");l(e,h);e.id=a;e.href=d;e.style.cssText=c;return e}function p(a,b,d){if(!a)return!1;if(a.addEventListener)return a.addEventListener(b,d,!0),!0;if(a.attachEvent)return a.attachEvent("on"+b,d)}function q(a,b,d){if(!a)return!1;if(a.addEventListener)return a.removeEventListener(b,
d),!0;if(a.attachEvent)return a.detachEvent("on"+b,d)}function e(a){try{0<b.location.href.indexOf("log=true")&&console.log("[optin]"+a)}catch(c){}}function x(){c("optin_leggi");return!0}function y(){return r("optin_ok")}function z(){return r("optin_close")}function r(a){try{e("_dismissLinkClick "+a);c(a);var h=A+"?value=1&r="+Math.floor(10*Math.random()+1),d=b.createElement("IFRAME");d.setAttribute("src",h);d.style.width="0px";d.style.height="0px";d.style.display="none";b.body.appendChild(d);e("createPolicyCookie created");
v();e("_dismissLinkClick  END "+a)}catch(f){}return!1}function B(c){try{null!=b.getElementById("cookieChoiceInfo")?(e("register Scroll"),r("optin_Scroll"),e(q(a,"scroll",t)),u(c),e("register  1END Scroll")):e("banner not present Scroll")}catch(h){e("detect tree check")}}function C(){a.setTimeout(function(){e("start 1.44");try{$("cookieChoiceInfo").fadeIn(1E3)}catch(a){e("jquery not found")}try{b.getElementById("cookieChoiceInfo").style.opacity=1}catch(a){}},2E3)}function t(c){if(null!=b.getElementById("cookieChoiceInfo")){e("register 1.43");
var h=0;try{for(var d=c.target;d;){if(d.id&&("cookieChoiceDismiss2"==d.id||"cookieChoiceDismiss"==d.id)){h=1;e("found OK or x");break}else if(d.id&&"cookieChoiceInfo"==d.id){e("found cookieConsentId");h=1;break}d=d.parentNode}}catch(f){e("detect tree check")}0==h&&r("optin_click");try{if(0==h)for(var g=c.target;g;){if(g.href&&""!==g.href){e("href event "+g.href);c.preventDefault();break}else e("rec else:"+g);g=g.parentNode}}catch(f){e("errr evnet listener")}e(q(a,"click",t));0==h&&u(c);e("register END ")}else e("banner not present")}
function u(a){a.stopPropagation?a.stopPropagation():a.returnValue=!1}function D(a){u(a)}function v(){if(null!=b.getElementById("cookieChoiceInfo")){var a=b.getElementById("cookieChoiceInfo");a.parentNode.removeChild(a)}}function E(){if(null==w("policy_cookie"))return!0;var a=w("policy_cookie").split("_")[0],c=a.charAt(1),d=a.charAt(2);if(a.length!=F.length){if("1"==c||"1"==d)return e(c+","+d),!1;a=iolcookcs.policyCookieName;c=new Date;c.setTime(c.getTime()+-864E5);c="; expires="+c.toGMTString();b.cookie=
a+"="+c+"; path=/";return!0}return!1}function w(a){a+="=";for(var c=b.cookie.split(";"),d=0;d<c.length;d++){for(var e=c[d];" "==e.charAt(0);)e=e.substring(1,e.length);if(0==e.indexOf(a))return e.substring(a.length,e.length)}return null}var F="DataRecs geo vlocal Advertising tmp1 tmp2 af xedge".split(" "),A=("https:"==b.location.protocol?"https:":"http:")+"//privacy.italiaonline.it/common/cookie/api/set_policy_cookie.php";return{displayCookieBanner:function(){if(E())try{v();var f;if(iol&&iol.overload)e("oveloading tooltip"),
f=iol.overload._createHeaderElement("cookieChoiceInfo","cookieChoiceDismiss","cookieChoiceDismiss2","http://privacy.italiaonline.it/common/cookie/privacy_detail.php?from=banner","leggiLinkIdp");else{e("base tooltip");var h=b.createElement("div");h.id="cookieChoiceInfo";h.style.cssText="opacity:0; text-align:left; font-family: Arial,Helvetica,sans-serif; position: fixed; z-index: 100000000; background: none repeat scroll 0% 0% rgb(22, 121, 195); padding: 5px 25px; line-height: 14px; font-size:14px;  left: 0px; top: 0px; color:#fff;margin: 10px 20px;";
var d=b.createElement("div");d.style.cssText="margin: px 01px";d.appendChild(m("cookieChoiceDismiss","X","vertical-align: middle; color: rgb(255, 255, 255); font-weight: bold; font-family: Tahoma,Geneva,sans-serif; font-size: 15px; text-decoration: none; position:absolute; right:7px; top:5px"));d.appendChild(n("Questo sito utilizza cookie anche di terzi per inviarti pubblicita' e servizi in linea con le tue preferenze. Se vuoi saperne di piu' o negare il consenso a tutti o ad alcuni cookie, ","vertical-align:middle;color: rgb(255, 255, 255);"));
d.appendChild(k("leggiLinkIdp","leggi qui","http://privacy.italiaonline.it/common/cookie/privacy_detail.php?from=banner","vertical-align:middle;color:#FFF; font-weight:bold; text-decoration:none"));d.appendChild(n(". Chiudendo questo banner, scorrendo questa pagina o cliccando qualunque elemento acconsenti all'uso dei cookie.","vertical-align:middle;color: rgb(255, 255, 255);"));d.appendChild(m("cookieChoiceDismiss2","OK","vertical-align: middle; color: rgb(22, 121, 195); font-weight: bold; background: none repeat scroll 0% 0% rgb(238, 238, 238); text-decoration: none; display: inline-block; padding:1px 10px; line-height: 16px; margin: 2px 0px 0px 10px;"));
h.appendChild(d);c("optin_viewtoolbar");f=h}var l=b.createDocumentFragment();l.appendChild(f);b.body.appendChild(l.cloneNode(!0));b.getElementById("cookieChoiceDismiss").onclick=z;b.getElementById("cookieChoiceDismiss2").onclick=y;b.getElementById("leggiLinkIdp").onclick=x;p(a,"click",t);p(a,"scroll",B);C();p("cookieChoiceInfo","click",D)}catch(q){e("showBar problem ")}}}}();a.iolp={cookieChoices:c};return c})(this);iolp.cookieChoices.displayCookieBanner();window.setTimeout(function(){try{iol.dmp2.semtrack()}catch(a){iol.dmp2.log("semtrackAsync")}},
6E3)});iol.iolcookcs.trackCookie=function(a){try{var b=("https:"==document.location.protocol?"https:":"http:")+"//privacy.italiaonline.it/common/cookie/api/set_policy_cookie.php?trvalue="+a+"&r="+Math.floor(10*Math.random()+1),f=document.createElement("IFRAME");f.setAttribute("src",b);f.style.width="0px";f.style.height="0px";f.style.display="none";window.setTimeout(function(){document.body.appendChild(f)},3E3)}catch(c){}};
iol.iolcookcs.isCookieEnable=function(a){for(var b="DataRecs geo vlocal Advertising tmp1 tmp2 af xedge".split(" "),f="",c=document.cookie.split(";"),g=0;g<c.length;g++){for(var l=c[g];" "==l.charAt(0);)l=l.substring(1,l.length);0==l.indexOf("policy_cookie=")&&(f=l.substring(14,l.length))}if(null!=f&&""!=f){f=f.split("_")[0];c=null;for(index=0;index<b.length;++index)if(b[index]==a){c=index;break}a=null!=c?f.charAt(c):null}else return!0;return"1"==a?!0:!1};
iol.dmp2.semtrackAsync=function(a){try{var b=iol.dmp2.detectbcp();if("undefined"!=typeof a.stes){if("string"==typeof a.stes.tag)b.add("genp","sem:"+a.stes.tag),iol.dmp2.log(a.stes.tag);else for(var f=0;f<a.stes.tag.length;f++)b.add("genp","sem:"+a.stes.tag[f]),iol.dmp2.log(a.stes.tag[f]);b.bcp()}else iol.dmp2.log("nessun val")}catch(c){iol.dmp2.log("semtrackAsync")}};
iol.dmp2.semtrack=function(){try{iol.dmp2.log("Start semtrack "+document.location.href.length),"undefined"!=typeof iol.dmp2.detectbcp()?35<document.location.href.length&&(iol.dmp2.log("url OK"),iol.dmp2.getSemInfo()):iol.dmp2.log("sem stop bcp nt")}catch(a){iol.dmp2.log("semtrack")}};
iol.dmp2.detectbcp=function(){var a;"undefined"!=typeof _cc6200?a=_cc6200:"undefined"!=typeof _cc6206?a=_cc6206:"undefined"!=typeof _cc6202?a=_cc6202:"undefined"!=typeof _cc6205?a=_cc6205:"undefined"!=typeof _cc6207?a=_cc6207:"undefined"!=typeof _cc6204?a=_cc6204:"undefined"!=typeof _cc6233?a=_cc6233:"undefined"!=typeof _cc6328?a=_cc6328:"undefined"!=typeof _cc6775?a=_cc6775:"undefined"!=typeof _cc6235?a=_cc6235:"undefined"!=typeof _cc6367?a=_cc6367:"undefined"!=typeof _cc6232?a=_cc6232:"undefined"!=
typeof _cc6348?a=_cc6348:"undefined"!=typeof _cc8516?a=_cc8516:iol.dmp2.log("bcp non trovato");return a};iol.dmp2.getSemUrl=function(){try{var a=document.location.href;-1<a.indexOf("https://")&&(a="");-1<a.indexOf("?")&&(a=a.substring(0,a.indexOf("?")));iol.dmp2.log("clean "+a);if(""!=a)return"http://tuttosu.virgilio.it/all-about-api/tags_service_tutto_su.php?id="+encodeURIComponent(a)+"&format=jsonp&callback=iol.dmp2.semtrackAsync";iol.dmp2.log("http://tuttosu.virgilio.it/index.php");return""}catch(b){}};
iol.dmp2.log=function(a){try{0<document.location.href.indexOf("log=true")&&console.log("[dmp]"+a)}catch(b){}};iol.dmp2.getSemInfo=function(){try{var a=this.getSemUrl();if(""!=a){var b=document.createElement("script");b.type="text/javascript";b.src=a;window.setTimeout(function(){try{document.body.appendChild(b)}catch(a){}},3E3)}}catch(f){iol.dmp2.log("getSemInfo")}};
iol.track.regTracking=function(){try{iol.dmp2.log("start timeout track"),35<document.location.href.length?window.setTimeout(function(){try{iol.track.Tracking()}catch(a){}},3E3):iol.dmp2.log("no track")}catch(a){iol.dmp2.log("regTracking")}};
iol.track.Tracking=function(){try{iol.dmp2.log("track ");var a=window.location.href,b=document.referrer;-1<a.indexOf("?")&&(a=a.substring(0,a.indexOf("?")));var b=b+"/",f="";iol.dmp2.log("track referer "+b);iol.dmp2.log("track url "+a);if(-1!=b.indexOf("google.")||-1!=b.indexOf("bing.")){iol.dmp2.log("track seo ");var c="",g=b.indexOf("&q=");-1==g&&(g=b.indexOf("?q="));iol.dmp2.log("track seo 2 "+g);if(-1!=g)var l=b.indexOf("&",g+1),c=b.substring(g+1,l)+"&",c=c.replace("q=","q=seo_");iol.dmp2.log("track seo 3 "+
c);var n=b.indexOf("http://"),m=b.indexOf("/",7);-1==n&&(n=b.indexOf("https://"),m=b.indexOf("/",8),-1==m&&(m=b.length),iol.dmp2.log("track seo 3 https "+n+", "+m));var k=b.substring(0,m).replace("http://","").replace("https://","");try{-1!=k.indexOf("http")&&(k=10<k.length?"f"+k.substring(0,9):"f"+k)}catch(e){}""==c&&(c="q="+k+"&");f=c+"d="+k;iol.dmp2.log("track seo 4 "+f)}else if(b.indexOf("facebook.")||b.indexOf("twitter.")){iol.dmp2.log("track social ");n=b.indexOf("http://");m=b.indexOf("/",
7);-1==n&&(b.indexOf("https://"),m=b.indexOf("/",8));k=b.substring(0,m).replace("http://","").replace("https://","");try{-1!=k.indexOf("http")&&(k=10<k.length?"f"+k.substring(0,9):"f"+k)}catch(e){}f="q="+k+"&d="+k}g=c="";-1!=a.indexOf("dilei.it")?g="IVD_":-1!=a.indexOf("motori.virgilio.it")?g="IVM_":-1!=a.indexOf("quifinanza.it")?g="IVF_":-1!=a.indexOf("siviaggia.it")?g="IVV_":-1!=a.indexOf("supereva.it")?(a=a.replace(RegExp("-","g"),"/"),iol.dmp2.log("Adapting supereva -/"),g="ISE_"):-1!=a.indexOf("sportstadio.it")?
g="IWN_":iol.dmp2.log("no dominio track");if(g)if(-1!=a.indexOf("/attachment/"))var p=a.indexOf("/attachment/"),c=a.substring(a.lastIndexOf("/",p-1)+1,p).replace("/","");else c=a.substring(a.lastIndexOf("/",a.length-2)+1).replace("/","");p=/^\d+$/;""==c||p.test(c)?c=g+c:(iol.dmp2.log("ID not detected"),c="");if(""!=c&&""!=b){var q=document.createElement("img");q.type="text/javascript";q.src="http://kpi.plug.it/tracks/bi/images/RT_A.gif?link="+a+"&"+f+"&id=C_"+c+"&rand="+Math.floor(1E7*Math.random()+
1);iol.dmp2.log("track url.src "+q.src);document.body.appendChild(q)}}catch(e){iol.dmp2.log("Tracking")}};iol.track.regTracking();
